services:
    web:
        image: ghcr.io/openstatushq/agent-webhook:latest
        platform: linux/amd64
        env_file: .env
        ports:
            - "3000:3000"
        restart: unless-stopped
        read_only: true
        tmpfs:
            - /tmp
        security_opt:
            - no-new-privileges:true
        cap_drop:
            - ALL
